version: '3'

services:
  api:
    image: phillipkhne/docker_compose_cityfix:cityfix_api
    build: ./cityfix_api/
    volumes:
      - ${BACKENDDIR}:/root/workspace

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=true
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ESDATA}:/usr/share/elasticsearch/data
    ports: 
      - "9300:9300"
      - "9200:9200"