#Composefile für die Einrichtung zur Auslieferung auf dem Server. Momentan unvollständig.
version: '3'

services:
  apache:
    image: phillipkhne/docker_compose_cityfix:cityfix_apache_prod
    build: ./cityfix_apache_prod/
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/test:/var/www/
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.master=true
      - node.data=true
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - "9300:9300"
      - "9200:9200"

  phpdev:
    image: phillipkhne/docker_compose_cityfix:cityfix_api
    container_name: phpdev
    volumes:
      - /tmp/test/backend:/root/workspace
    command: sh -c "composer update && php artisan locations:fetch"
    depends_on:
      - elasticsearch

volumes:
  esdata: